plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - 'config/boot.rb'
    - 'config/environment.rb'
    - 'config/application.rb'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'Rakefile'
    - 'config.ru'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'db/schema.rb'

Layout/LineLength:
  Max: 120